apiVersion: v1
kind: Namespace
metadata:
  name: openshift-opentelemetry-operator
  labels:
    openshift.io/cluster-monitoring: "true"

    # kubernetes.io/metadata.name: openshift-opentelemetry-operator
    # pod-security.kubernetes.io/audit: restricted
    # pod-security.kubernetes.io/audit-version: latest
    # pod-security.kubernetes.io/warn: restricted
    # pod-security.kubernetes.io/warn-version: latest
    # security.openshift.io/scc.podSecurityLabelSync: "true"
  # annotations:
  #   openshift.io/sa.scc.mcs: s0:c29,c19
  #   openshift.io/sa.scc.supplemental-groups: 1000850000/10000
  #   openshift.io/sa.scc.uid-range: 1000850000/10000
