kind: Secret
apiVersion: v1

metadata:

  name: loki-bucket-secret
  namespace: openshift-logging

data:
  access_key_id: eUdXNGdHOU1RMmg5aFhzWEh5UG4=
  access_key_secret: d2VjWmMwbDZyakplSG93c0JjRFZtTjVjc0gwL204Y3YyQWd1ZHh6UA==
  bucketnames: bG9raS1sb2dz
  endpoint: aHR0cDovL21pbmlvLXNlcnZpY2Uub3BlbnNoaWZ0LWxvZ2dpbmcuc3ZjOjkwMDA=
  region: ZXUtY2VudHJhbC0x

type: Opaque
