kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
  namespace: openshift-logging

spec:

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem