kind: Namespace
apiVersion: v1
metadata:
  name: openshift-logging

  # labels:
  #   kubernetes.io/metadata.name: openshift-logging
  #   pod-security.kubernetes.io/audit: privileged
  #   pod-security.kubernetes.io/audit-version: latest
  #   pod-security.kubernetes.io/warn: privileged
  #   pod-security.kubernetes.io/warn-version: latest
  #   security.openshift.io/scc.podSecurityLabelSync: 'true'
  # annotations:
  #   openshift.io/sa.scc.mcs: 's0:c30,c15'
  #   openshift.io/sa.scc.supplemental-groups: 1000900000/10000
  #   openshift.io/sa.scc.uid-range: 1000900000/10000
