apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:

  # annotations:
  #   olm.providedAPIs: Central.v1alpha1.platform.stackrox.io,SecuredCluster.v1alpha1.platform.stackrox.io,SecurityPolicy.v1alpha1.config.stackrox.io

  generateName: open-cluster-management-

  name: open-cluster-management
  namespace: open-cluster-management

spec:
  targetNamespaces:
  - open-cluster-management
  upgradeStrategy: Default
