kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
  name: otel-demo

spec:
  config:
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    exporters:
      debug: {}
      otlp:
        endpoint: 'tempo-tempo-trace-demo-distributor.demo.svc.cluster.local:4317'
        tls:
          insecure: true
      otlphttp:
        endpoint: https://logging-loki-gateway-http.demo.svc.cluster.local:8080/api/logs/v1/application/otlp
        encoding: json
        tls:
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        auth:
          authenticator: bearertokenauth

    processors:
      k8sattributes: {}
      resource:
        attributes:
          - key:  kubernetes.namespace_name
            from_attribute: k8s.namespace.name
            action: upsert
          - key:  kubernetes.pod_name
            from_attribute: k8s.pod.name
            action: upsert
          - key: kubernetes.container_name
            from_attribute: k8s.container.name
            action: upsert
          - key: log_type
            value: application
            action: upsert
      transform:
        log_statements:
          - context: log
            statements:
              - set(attributes["level"], ConvertCase(severity_text, "lower"))

    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    service:
      extensions: 
        - bearertokenauth 
      pipelines:
        logs:
          exporters:
            - debug
            - otlphttp
          receivers:
            - otlp

        metrics:
          exporters:
            - debug
          receivers:
            - otlp

        traces:
          exporters:
            - debug
            - otlp
          receivers:
            - otlp
