apiVersion: v1
kind: Namespace
metadata:
  name: oadp
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: ""
    # openshift.io/sa.scc.mcs: s0:c31,c10
    # openshift.io/sa.scc.supplemental-groups: 1000950000/10000
    # openshift.io/sa.scc.uid-range: 1000950000/10000
  # labels:
  #   kubernetes.io/metadata.name: oadp
  #   pod-security.kubernetes.io/audit: privileged
  #   pod-security.kubernetes.io/audit-version: latest
  #   pod-security.kubernetes.io/enforce: privileged
  #   pod-security.kubernetes.io/warn: privileged
  #   pod-security.kubernetes.io/warn-version: latest
