apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:

  labels:
    operators.coreos.com/quay-operator.openshift-operators: ""
  name: quay-operator
  namespace: openshift-operators

spec:
  channel: stable-3.15
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: quay-operator.v3.15.2
  # installPlanApproval: Automatic